/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type RunQueryDto = {
  /**
   * The prompt to send to the LLM
   *
   * @example Tell me a story about a brave knight.
   */
  prompt: string
  /**
   * Maximum number of tokens to generate
   *
   * @example 100
   */
  maxTokens?: number
}

export type QueryResponseDto = {
  /**
   * The response from the LLM
   */
  response: string
}
